# Generated by Django 5.1.4 on 2024-12-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Book name')),
                ('author', models.CharField(max_length=60, verbose_name='Book author')),
                ('price', models.PositiveIntegerField(verbose_name='Book price')),
                ('image', models.ImageField(upload_to='books', verbose_name='Book images')),
            ],
        ),
    ]
