# Generated by Django 5.1.4 on 2024-12-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
